import express, { type Express, type Request, type Response } from "express";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { ulid } from "ulid";
import type Database from "better-sqlite3";
import type { Client, GuildMember } from "discord.js";
import type { Config } from "../config.js";
import type { Clock } from "../clock.js";
import type { EventSink, LogEvent } from "../stores/EventSink.js";
import type { DiscordPort } from "../domain/reportMachine.js";
import { advanceShift, applyReport, ClosedInstanceError, DiscordPostError, DiscordTickError } from "../domain/reportMachine.js";
import { isKind, isRoom } from "../domain/rooms.js";
import { createInstanceFlow, CapError, NotSetupError, ThrottleError, BotPermsError, UnthreadedConflictError } from "../discord/createInstance.js";
import { getGuildSettings } from "../stores/guildSettings.js";
import { getInstance } from "../stores/instances.js";
import { listReports, occupancy } from "../stores/reports.js";
import { withRoomLock } from "../stores/locks.js";
import { isTombstoned } from "../domain/tombstone.js";
import { inviteUrl, memberCanStart } from "../discord/permissions.js";
import { memberCanViewChannel, memberDisplayName } from "./permissions.js";
import { authorizeUrl, exchangeCode, fetchMe, fetchUserGuilds } from "./oauth.js";
import { COOKIE_NAME, cookieHeader, signSession, unsignSession } from "./cookies.js";
import { CSRF_COOKIE, csrfOk, newCsrfToken } from "./csrf.js";
import { startPage } from "./views/start.js";
import { instancePage, type SnapshotRow } from "./views/instance.js";
import { sign, unsign } from "cookie-signature";

const DAY = 604800;
const oauthTokens = new Map<string, string>();
function cookies(req: Request): Record<string, string> { return Object.fromEntries((req.headers.cookie ?? "").split(";").map((part) => { const i = part.indexOf("="); return i < 0 ? ["", ""] : [part.slice(0, i).trim(), decodeURIComponent(part.slice(i + 1))]; }).filter(([key]) => key)); }
function session(req: Request, secret: string): string | null { const value = cookies(req)[COOKIE_NAME]; return value ? unsignSession(value, secret) : null; }
function relative(value: unknown): string { return typeof value === "string" && value.startsWith("/") && !value.startsWith("//") ? value : "/"; }
function shortError(error: unknown): { status: number; message: string } { if (error instanceof ThrottleError) return { status: 429, message: "Slow down. Max 3 sessions per minute." }; if (error instanceof CapError) return { status: 429, message: "This server already has 20 open sessions." }; if (error instanceof NotSetupError) return { status: 400, message: "set an output channel" }; if (error instanceof BotPermsError) return { status: 400, message: `Bot is missing permissions: ${error.message}` }; if (error instanceof UnthreadedConflictError) return { status: 409, message: error.message }; if (error instanceof Error) return { status: 400, message: error.message }; return { status: 400, message: String(error) }; }
function rows(db: Database.Database, instance: { shiftNumber: number; createdAt: string; id: string }): SnapshotRow[] { return [{ type: "banner", text: `---- SHIFT ${instance.shiftNumber} ----`, createdAt: instance.createdAt }, ...listReports(db, instance.id).map((report) => ({ type: "report" as const, report }))]; }
function payload(db: Database.Database, instance: NonNullable<ReturnType<typeof getInstance>>, clock: Clock, timeZone: string) { return { occupancy: occupancy(db, instance.id), rows: rows(db, instance), closed: Boolean(instance.closedAt), timeZone, now: clock.now().toISOString() }; }

export function createWebApp(opts: { config: Config; db: Database.Database; client: Client; clock: Clock; events: EventSink; discordPort: DiscordPort }): Express {
  const app = express();
  if (opts.config.trustProxy) app.set("trust proxy", true);
  app.use(express.urlencoded({ extended: false })); app.use(express.json());
  app.use("/static", express.static(path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../public")));
  const requireAuth = (req: Request, res: Response): string | null => { const id = session(req, opts.config.sessionSecret); if (!id) { res.redirect(`/login?returnTo=${encodeURIComponent(req.originalUrl)}`); return null; } return id; };
  const secure = opts.config.publicBaseUrl.startsWith("https://") || opts.config.trustProxy;

  app.get("/login", (req, res) => { const state = sign(JSON.stringify({ returnTo: relative(req.query.returnTo) }), opts.config.sessionSecret); res.redirect(authorizeUrl({ clientId: opts.config.discordClientId, redirectUri: `${opts.config.publicBaseUrl}/oauth/callback`, state })); });
  app.get("/oauth/callback", async (req, res) => { try { const state = typeof req.query.state === "string" ? unsign(req.query.state, opts.config.sessionSecret) : false; const parsed = state ? JSON.parse(state) as { returnTo?: string } : {}; const code = typeof req.query.code === "string" ? req.query.code : ""; if (!code || !state) return res.status(400).send("Invalid OAuth callback."); const token = await exchangeCode({ clientId: opts.config.discordClientId, clientSecret: opts.config.discordClientSecret, redirectUri: `${opts.config.publicBaseUrl}/oauth/callback`, code }); const me = await fetchMe(token.accessToken); oauthTokens.set(me.id, token.accessToken); res.setHeader("Set-Cookie", cookieHeader(COOKIE_NAME, signSession(me.id, opts.config.sessionSecret), { maxAgeSec: DAY, secure })); res.redirect(relative(parsed.returnTo)); } catch { res.status(502).send("OAuth failed."); } });
  app.get("/", async (req, res) => { const userId = requireAuth(req, res); if (!userId) return; try { const csrf = newCsrfToken(); res.setHeader("Set-Cookie", cookieHeader(CSRF_COOKIE, csrf, { maxAgeSec: DAY, secure })); const userGuilds = await fetchUserGuilds(oauthTokens.get(userId) ?? ""); const mutual = userGuilds.filter((guild) => getGuildSettings(opts.db, guild.id) && opts.client.guilds.cache.has(guild.id)); res.send(startPage({ csrf, guilds: mutual, inviteUrl: inviteUrl(opts.config.discordClientId) })); } catch { res.status(502).send("Unable to load guilds."); } });
  app.post("/start", async (req, res) => { const userId = requireAuth(req, res); if (!userId) return; const cs = cookies(req)[CSRF_COOKIE]; if (!csrfOk({ cookieToken: cs, bodyToken: req.body.csrf, origin: req.headers.origin, referer: req.headers.referer, publicBaseUrl: opts.config.publicBaseUrl })) return res.status(403).send("Invalid CSRF."); const guildId = String(req.body.guildId ?? ""); const settings = getGuildSettings(opts.db, guildId); try { if (!settings || !opts.client.guilds.cache.has(guildId)) return res.status(400).send("set an output channel"); const guild = await opts.client.guilds.fetch(guildId); const member = await guild.members.fetch(userId); const channel = await opts.client.channels.fetch(settings.defaultChannelId); const perms = channel && "permissionsFor" in channel ? (channel as any).permissionsFor(member)?.bitfield ?? 0n : 0n; if (!memberCanStart(perms)) return res.status(403).send("You need View Channel and Send Messages in the output channel."); const result = await createInstanceFlow({ db: opts.db, client: opts.client, config: opts.config, clock: opts.clock, events: opts.events, guildId, actorId: userId, actorDisplayName: member.displayName, actorPermissions: perms, mode: "user" }); res.redirect(`/g/${guildId}/i/${result.instance.id}`); } catch (error) { const e = shortError(error); res.status(e.status).send(e.message); } });

  const getAuthorized = async (req: Request, res: Response) => { const userId = requireAuth(req, res); if (!userId) return null; const instanceId = String(req.params.instanceId ?? ""); const guildId = String(req.params.guildId ?? ""); const instance = getInstance(opts.db, instanceId); const settings = getGuildSettings(opts.db, guildId); if (!instance || instance.guildId !== guildId || isTombstoned(instance, settings, opts.clock.now())) { res.status(404).send("Not found."); return null; } if (!await memberCanViewChannel(opts.client, guildId, instance.parentChannelId, userId)) { res.status(403).send("Forbidden."); return null; } return { userId, instance, settings: settings! }; };
  app.get("/g/:guildId/i/:instanceId", async (req, res) => { const auth = await getAuthorized(req, res); if (!auth) return; const csrf = newCsrfToken(); res.setHeader("Set-Cookie", cookieHeader(CSRF_COOKIE, csrf, { maxAgeSec: DAY, secure })); res.send(instancePage({ csrf, guildId: req.params.guildId, instanceId: auth.instance.id, shiftNumber: auth.instance.shiftNumber, closed: Boolean(auth.instance.closedAt), occupancy: occupancy(opts.db, auth.instance.id), rows: rows(opts.db, auth.instance), timeZone: auth.settings.timezone, tickMark: "✅" })); });
  app.get("/g/:guildId/i/:instanceId/poll", async (req, res) => { const auth = await getAuthorized(req, res); if (!auth) return; res.json(payload(opts.db, auth.instance, opts.clock, auth.settings.timezone)); });
  app.get("/g/:guildId/i/:instanceId/events", async (req, res) => { const auth = await getAuthorized(req, res); if (!auth) return; res.setHeader("Content-Type", "text/event-stream"); res.setHeader("Cache-Control", "no-cache"); res.setHeader("Connection", "keep-alive"); res.flushHeaders(); res.write(`data: ${JSON.stringify({ type: "hello", ...payload(opts.db, auth.instance, opts.clock, auth.settings.timezone) })}\n\n`); const send = (ev: LogEvent) => { if (ev.instanceId === auth.instance.id) res.write(`data: ${JSON.stringify(ev)}\n\n`); }; const unsubscribe = opts.events.subscribe(auth.instance.id, send); const heartbeat = setInterval(() => res.write(":ping\n\n"), 15000); req.on("close", () => { clearInterval(heartbeat); unsubscribe(); }); });
  app.post("/g/:guildId/i/:instanceId/shift", async (req, res) => { const auth = await getAuthorized(req, res); if (!auth) return; if (!csrfOk({ cookieToken: cookies(req)[CSRF_COOKIE], bodyToken: req.body.csrf, origin: req.headers.origin, referer: req.headers.referer, publicBaseUrl: opts.config.publicBaseUrl })) return res.status(403).json({ ok: false, error: "Invalid CSRF." }); try { const name = await memberDisplayName(opts.client, auth.instance.guildId, auth.userId, "Unknown"); const result = await advanceShift({ db: opts.db, instance: auth.instance, userId: auth.userId, displayName: name, clock: opts.clock, events: opts.events, discord: opts.discordPort, newId: ulid }); res.json({ ok: true, shiftNumber: result.shiftNumber }); } catch (error) { if (error instanceof ClosedInstanceError) return res.status(409).json({ ok: false, error: "Session closed." }); if (error instanceof DiscordPostError) return res.status(502).json({ ok: false, error: error.message }); res.status(400).json({ ok: false, error: error instanceof Error ? error.message : String(error) }); } });

  app.post("/g/:guildId/i/:instanceId/report", async (req, res) => { const auth = await getAuthorized(req, res); if (!auth) return; if (!csrfOk({ cookieToken: cookies(req)[CSRF_COOKIE], bodyToken: req.body.csrf, origin: req.headers.origin, referer: req.headers.referer, publicBaseUrl: opts.config.publicBaseUrl })) return res.status(403).json({ ok: false, error: "Invalid CSRF." }); if (auth.instance.closedAt) return res.status(409).json({ ok: false, error: "Session closed." }); const room = String(req.body.room ?? ""); const kind = String(req.body.kind ?? "ANOMALY"); if (!isRoom(room) || !isKind(kind)) return res.status(400).json({ ok: false, error: "Invalid room or kind." }); try { const name = await memberDisplayName(opts.client, auth.instance.guildId, auth.userId, "Unknown"); const result = await withRoomLock(auth.instance.id, room, () => applyReport({ db: opts.db, instance: auth.instance, room, kind, userId: auth.userId, displayName: name, tickEmoji: auth.settings.tickEmoji, clock: opts.clock, events: opts.events, discord: opts.discordPort, newId: ulid })); res.json({ ok: true, result: result.type, occupancy: occupancy(opts.db, auth.instance.id), report: result.report }); } catch (error) { if (error instanceof ClosedInstanceError) return res.status(409).json({ ok: false, error: "Session closed." }); if (error instanceof DiscordTickError || error instanceof DiscordPostError) return res.status(502).json({ ok: false, error: error.message }); res.status(400).json({ ok: false, error: error instanceof Error ? error.message : String(error) }); } });
  return app;
}
